version: "2"

services:
  www:
    build: .
    ports:
      - 5000:5000
    user: uwsgi
    environment:
      DEBUG: 1
      REDIS_URL: 'redis://redis:6379'
    volumes:
      - ./src:/app
    links:
      - redis:redis

  redis:
    image: redis
