version: "2"

services:
  www:
    build: www
    ports:
      - 5000:5000
    user: nobody
    environment:
      DEBUG: 1
    volumes:
      - ./src:/app
    links:
      - redis:redis

  redis:
    image: redis
