---
apiVersion: v1
kind: Service
metadata:
  name: trainingwheels
  labels:
    name: trainingwheels
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 5000
  selector:
    name: trainingwheels
