---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "trainingwheels.fullname" . }}
  labels:
    app: {{ template "trainingwheels.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.monitoring.serviceMonitorName }}
    servicemonitor: {{ .Values.monitoring.serviceMonitorName }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: web
  selector:
    app: {{ template "trainingwheels.name" . }}
    release: {{ .Release.Name }}
